# Template for dataset path

artifacts_root: artifacts

data_injection:
  root_dir: artifacts/data_injection
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/refs/heads/master/summarizer-data.zip
  local_data_file: artifacts/data_injection/data.zip
  unzip_dir: artifacts/data_injection



data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "validation"]


data_transformation:
  root_dir:  artifacts/data_transformration
  data_path: artifacts/data_injection/samsum_dataset
  tokenizer_name: "t5-small"
